#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '2':
        pose: Object/pose
        pose2d: Object/ground_pose
        odom: Object/Odom
        tf: tf
        child_frame_id: Object/base_link
        parent_frame_id: Origin/base_link
    '3':
        pose: Origin/pose
        pose2d: Origin/ground_pose
        odom: Origin/Odom
        tf: tf
        child_frame_id: Origin/base_link
        parent_frame_id: mocap_world
optitrack_config:
        multicast_address: 239.255.42.99
        command_port: 1510
        data_port: 1511
        enable_optitrack: true
